version: "3.6"
services:
  database:
    container_name: rodas_database
    image: postgres

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rodas_com

    ports:
      - "5432:5432"

    volumes:
      - ./pgdata:/var/lib/postgresql/data
      # Copia o arquivo init.sql para o container
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    restart: always
